"""
database.py  —  SQLAlchemy ORM layer (PostgreSQL on Neon)
Table: code_analysis  — stores every codebase audit report
"""

import logging
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any

from sqlalchemy import (
    create_engine, Column, Integer, String, Text, Float, DateTime, Index, inspect, text
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from config import config

logger = logging.getLogger(__name__)

def _build_connect_args(url: str) -> Dict[str, Any]:
    if url.startswith("sqlite"):
        return {"check_same_thread": False}
    if "neon.tech" in url or "sslmode=require" in url:
        return {"sslmode": "require"}
    return {}


_connect_args: Dict[str, Any] = _build_connect_args(config.DATABASE_URL)

engine = create_engine(
    config.DATABASE_URL,
    connect_args=_connect_args,
    pool_pre_ping=True,
    pool_size=5,
    max_overflow=10,
    echo=False,
)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    pass


class CodeAnalysis(Base):
    """Stores every AI code audit generated by the system."""
    __tablename__ = "code_analysis"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    source_url       = Column(String(512), nullable=True)   # e.g. github.com/owner/repo
    owner            = Column(String(255), nullable=True)
    repo             = Column(String(255), nullable=True)
    repo_name        = Column(String(512), nullable=True)   # full display name
    pr_number        = Column(Integer, nullable=True)
    pr_title         = Column(String(1024), nullable=True)
    pr_author        = Column(String(255), nullable=True)
    files_analyzed   = Column(Integer, nullable=True)
    report_text      = Column(Text,    nullable=False)
    confidence_score = Column(Float,   nullable=True)
    overall_score    = Column(Float,   nullable=True)
    analyzed_at      = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    __table_args__ = (
        Index("ix_analysis_analyzed_at", "analyzed_at"),
        Index("ix_analysis_owner_repo",  "owner", "repo"),
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id":               self.id,
            "source_url":       self.source_url,
            "owner":            self.owner,
            "repo":             self.repo,
            "repo_name":        self.repo_name,
            "pr_number":        self.pr_number,
            "pr_title":         self.pr_title,
            "pr_author":        self.pr_author,
            "files_analyzed":   self.files_analyzed,
            "report_text":      self.report_text,
            "confidence_score": self.confidence_score,
            "overall_score":    self.overall_score,
            "analyzed_at":      self.analyzed_at.isoformat() if self.analyzed_at else None,
        }


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------

def init_db() -> bool:
    try:
        if config.DATABASE_URL.startswith("sqlite"):
            # Ensure local SQLite parent folder exists.
            db_path = config.DATABASE_URL.replace("sqlite:///", "", 1)
            if db_path and "/" in db_path:
                from pathlib import Path
                Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        Base.metadata.create_all(bind=engine)
        _migrate_code_analysis_table()
        logger.info("Database tables initialised.")
        return True
    except Exception as exc:
        logger.error("❌ Database init failed: %s", exc)
        return False


def _migrate_code_analysis_table() -> None:
    """Add newly introduced columns for older DBs without destructive migrations."""
    inspector = inspect(engine)
    tables = set(inspector.get_table_names())
    if "code_analysis" not in tables:
        return

    existing_columns = {c["name"] for c in inspector.get_columns("code_analysis")}
    missing = []
    if "pr_number" not in existing_columns:
        missing.append(("pr_number", "INTEGER"))
    if "pr_title" not in existing_columns:
        missing.append(("pr_title", "VARCHAR(1024)"))
    if "pr_author" not in existing_columns:
        missing.append(("pr_author", "VARCHAR(255)"))

    if not missing:
        return

    with engine.begin() as conn:
        for col, col_type in missing:
            conn.execute(text(f"ALTER TABLE code_analysis ADD COLUMN {col} {col_type}"))
    logger.info("Applied code_analysis table migration, added columns: %s", ", ".join(col for col, _ in missing))


def close_db() -> None:
    engine.dispose()
    logger.info("PostgreSQL pool disposed.")


# ---------------------------------------------------------------------------
# CRUD
# ---------------------------------------------------------------------------

def save_analysis(
    source_url: str,
    owner: str,
    repo: str,
    repo_name: str,
    files_analyzed: int,
    report_text: str,
    confidence_score: Optional[float] = None,
    overall_score: Optional[float] = None,
    pr_number: Optional[int] = None,
    pr_title: Optional[str] = None,
    pr_author: Optional[str] = None,
) -> Optional[int]:
    with SessionLocal() as session:
        try:
            record = CodeAnalysis(
                source_url=source_url,
                owner=owner,
                repo=repo,
                repo_name=repo_name,
                pr_number=pr_number,
                pr_title=pr_title,
                pr_author=pr_author,
                files_analyzed=files_analyzed,
                report_text=report_text,
                confidence_score=confidence_score,
                overall_score=overall_score,
                analyzed_at=datetime.now(timezone.utc),
            )
            session.add(record)
            session.commit()
            session.refresh(record)
            logger.info("Analysis saved: id=%s  %s", record.id, repo_name)
            return record.id
        except Exception as exc:
            session.rollback()
            logger.error("Failed to save analysis: %s", exc)
            return None


def get_analysis_history(limit: int = 20, skip: int = 0) -> List[Dict[str, Any]]:
    with SessionLocal() as session:
        try:
            rows = (
                session.query(CodeAnalysis)
                .order_by(CodeAnalysis.analyzed_at.desc())
                .offset(skip).limit(limit).all()
            )
            return [r.to_dict() for r in rows]
        except Exception as exc:
            logger.error("Failed to fetch history: %s", exc)
            return []


def count_analyses() -> int:
    with SessionLocal() as session:
        try:
            return session.query(CodeAnalysis).count()
        except Exception:
            return 0


def get_analysis_by_id(analysis_id: int) -> Optional[Dict[str, Any]]:
    with SessionLocal() as session:
        try:
            row = session.query(CodeAnalysis).filter(CodeAnalysis.id == analysis_id).first()
            return row.to_dict() if row else None
        except Exception:
            return None


# Backward-compatible aliases expected by tests/docs from earlier API version.
def save_review(
    owner: str,
    repo: str,
    pr_number: int,
    pr_title: str,
    pr_author: str,
    review_text: str,
    confidence_score: Optional[float] = None,
    overall_score: Optional[float] = None,
) -> Optional[int]:
    return save_analysis(
        source_url=f"https://github.com/{owner}/{repo}/pull/{pr_number}",
        owner=owner,
        repo=repo,
        repo_name=f"{owner}/{repo}",
        pr_number=pr_number,
        pr_title=pr_title,
        pr_author=pr_author,
        files_analyzed=0,
        report_text=review_text,
        confidence_score=confidence_score,
        overall_score=overall_score,
    )


def get_review_history(limit: int = 20, skip: int = 0) -> List[Dict[str, Any]]:
    return get_analysis_history(limit=limit, skip=skip)


def count_total_reviews() -> int:
    return count_analyses()


def get_reviews_for_repo(owner: str, repo: str, limit: int = 20, skip: int = 0) -> List[Dict[str, Any]]:
    with SessionLocal() as session:
        try:
            rows = (
                session.query(CodeAnalysis)
                .filter(CodeAnalysis.owner == owner, CodeAnalysis.repo == repo)
                .order_by(CodeAnalysis.analyzed_at.desc())
                .offset(skip)
                .limit(limit)
                .all()
            )
            return [r.to_dict() for r in rows]
        except Exception as exc:
            logger.error("Failed to fetch repo reviews: %s", exc)
            return []
